name: "Build Package"

on:
  push:
    branches:
      - main
      - testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build Package
        run: nix build .#default --print-out-paths
